spring.application.name=mundoanimal
spring.datasource.url=jdbc:postgresql://dpg-d8fc1tt53gjs739vticg-a.oregon-postgres.render.com/mundo_animal_vbt8
spring.datasource.username=mundo_animal_vbt8_user
spring.datasource.password=mWgUSdWK9eGwNLnT5rgWVczcI1Vnwjmn

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.swagger-ui.path=/aula/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
server.port=${PORT:8080}